# Generated by Django 4.2.6 on 2023-10-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deptartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('service_title', models.CharField(max_length=200)),
                ('psga_time', models.IntegerField()),
                ('user_feedback', models.IntegerField()),
                ('up_down', models.IntegerField()),
                ('availability', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='eunnatapi.deptartment')),
            ],
        ),
    ]
